export const WEBSITE_KNOWLEDGE = [
  {
    keywords: [
      "entro",
      "entro ethiopia",
      "about entro",
      "tell me about entro",
      "what is entro",
      "who are you",
      "company",
      "software company",
      "ethiopian software company",
      "overview",
    ],
    answer:
      "Entro Ethiopia is a local software development company based in Addis Ababa, Ethiopia. We design and build practical, dependable digital solutions—including custom web applications, mobile apps, AI solutions, and ERP systems—specifically optimized to solve real challenges and work reliably in local operational conditions.",
  },
  {
    keywords: [
      "services",
      "web",
      "mobile",
      "development",
      "software",
      "solutions",
      "ui",
      "ux",
      "design",
      "erp",
      "custom",
      "offer",
      "provide",
      "build",
      "applications",
      "tailored",
      "business needs",
      "enterprise",
      "what we do",
    ],
    answer:
      "Entro Ethiopia offers top-tier software solutions tailored to your specific business needs. Our core services include:\n• Custom Web Application Development (React, Next.js, Node.js)\n• Mobile App Development (React Native & Expo)\n• UI/UX Design and Prototyping\n• Custom Enterprise Resource Planning (ERP), Inventory, and Property Management Platforms\n• AI Solutions & Automation (including MediCare AI)\n• IT Consulting and Software Architecture Design.",
  },
  {
    keywords: [
      "products",
      "software",
      "built",
      "management",
      "system",
      "portal",
      "apps",
      "app",
      "saas",
      "erp",
      "payroll",
      "todo",
      "projects",
      "portfolio",
      "platforms",
      "internal",
      "case studies",
    ],
    answer:
      "We have built several powerful products and custom platforms, including:\n1. EduStack: A premier K-12 school management network with AI multi-branch tools.\n2. MediCare AI: An intelligent hospital management platform reducing administrative workloads.\n3. Car Service Management System: Operational automation for auto service centers and garages.\n4. Employee Management System: A full-stack MERN platform for tracking attendance and payroll.\n5. Custom Corporate Client Implementations: Dedicated portals for clinics, tourism, advisory firms, and fleet services.",
  },
  {
    keywords: [
      "danat",
      "dental",
      "clinic",
      "healthcare",
      "booking",
      "dentist",
      "teeth",
      "appointments",
      "scheduling",
      "visibility",
      "ux",
    ],
    answer:
      "For Danat Dental Clinic, we designed and developed a modern, mobile-friendly, and SEO-ready website integrated with a centralized online patient booking system. This custom healthcare solution successfully reduced manual scheduling workloads, enhanced online credibility, and boosted digital visibility.",
  },
  {
    keywords: [
      "operation",
      "kilimanjaro",
      "tourism",
      "seo",
      "geo",
      "generative engine optimization",
      "search visibility",
      "discoverability",
      "reservations",
      "travel",
    ],
    answer:
      "For Operation Kilimanjaro, we implemented advanced technical SEO and Generative Engine Optimization (GEO) strategies alongside a structured tour booking system. This approach restructured content for maximum AI-driven search discoverability, streamlined reservation coordinates, and built powerful digital authority.",
  },
  {
    keywords: [
      "valintine",
      "advisors",
      "consulting",
      "advisory",
      "ai integration",
      "automation",
      "media visualization",
      "reporting",
      "dashboards",
      "workflows",
      "aggregation",
    ],
    answer:
      "For Valintine Advisors, we developed AI-driven automation systems to improve complex reporting workflows. The system automates manual data aggregation, introduces consistent media data visualization dashboards, cuts recurring process cycles down significantly, and upgrades decision-making speed.",
  },
  {
    keywords: [
      "afs",
      "automotive",
      "fleet",
      "services",
      "organogram",
      "chart",
      "organizational",
      "structure",
      "governance",
      "layout",
      "responsive",
    ],
    answer:
      "For AFS Automotive Fleet Services International PLC, we translated a static corporate organogram into a responsive, data-driven, and interactive web layout. It optimizes corporate governance viewing, works seamlessly across any screen dimension, and is structured for easy updates as organizational teams evolve.",
  },
  {
    keywords: [
      "industries",
      "serve",
      "who we serve",
      "clients",
      "smes",
      "ngos",
      "hospitals",
      "clinics",
      "government",
      "institutions",
      "businesses",
    ],
    answer:
      "Entro Ethiopia serves diverse fields with specialized systems. Our main industries include Small and Medium Enterprises (SMEs), Non-Governmental Organizations (NGOs), Clinics & Hospitals, Tourism & Booking services, Consulting/Advisory firms, and Government institutions looking for high-performance software built for local operational realities.",
  },
  {
    keywords: [
      "why local",
      "local matters",
      "conditions",
      "offline",
      "intermittent",
      "internet",
      "amharic",
      "english",
      "budgets",
      "pricing",
    ],
    answer:
      "Local matters because we build software tailored to Ethiopian business contexts, user skill sets, and infrastructure capabilities. Our systems feature smart offline modes to navigate intermittent internet, utilize intuitive and quick-to-learn interfaces, match local budgets without expensive imported pricing, and include dedicated close-proximity support in Amharic and English.",
  },
  {
    keywords: [
      "approach",
      "process",
      "phases",
      "listen",
      "workflow",
      "promise",
      "steps",
      "discovery",
      "planning",
    ],
    answer:
      "Our software approach centers on strict execution standards:\n1. Discovery & Requirement Analysis (Listen first, code second).\n2. System Architecture Planning (Tailoring architecture over templates).\n3. Phased Development & Testing (Delivering early working components).\n4. Deployment & Multi-Branch Integration.\n5. Ongoing Local Support & Optimization. Our core promise is simple: No unnecessary complexity, no vendor lock-in, and zero unanswered support tickets.",
  },
  {
    keywords: [
      "technology",
      "stack",
      "tech",
      "tools",
      "languages",
      "framework",
      "react",
      "nextjs",
      "tailwind",
      "nodejs",
      "express",
      "mongodb",
      "mern",
      "typescript",
      "backend",
      "frontend",
      "database",
      "coding",
      "python",
      "go",
      "postgresql",
    ],
    answer:
      "Our engineering team uses a cutting-edge tech stack:\n• Frontend: Next.js, React, Tailwind CSS, shadcn/ui\n• Backend: Node.js, Express, Python, Go\n• Database: MongoDB, PostgreSQL\n• Mobile: React Native, Expo",
  },
  {
    keywords: [
      "edustack",
      "school",
      "education",
      "academy",
      "kg-12",
      "institutions",
      "management",
      "multi-branch",
      "parent",
      "student",
      "portal",
      "academic",
      "insights",
      "teacherassist",
      "lesson planning",
      "classroom",
    ],
    answer:
      "EduStack is our premier education technology platform designed for KG-12 schools, academies, school networks, and educational institutions. It seamlessly combines school management, multi-branch operations, parent and student portals, AI-powered academic insights, and TeacherAssist AI for automated lesson planning and classroom support.",
  },
  {
    keywords: [
      "medicare",
      "healthcare",
      "hospital",
      "clinic",
      "medical",
      "patient",
      "laboratory",
      "pharmacy",
      "modules",
      "bed management",
      "billing",
      "diagnostic",
      "accuracy",
      "workload",
      "clinical",
    ],
    answer:
      "MediCare AI is our intelligent healthcare management platform that modernizes hospital operations with advanced AI features. It includes patient management, laboratory and pharmacy modules, bed management, and billing. It is proven to reduce administrative workload by 60% and significantly improve diagnostic accuracy.",
  },
  {
    keywords: [
      "medicare ai features",
      "clinical decision",
      "patient chatbot",
      "multi-llm",
      "ai assistant",
      "gpt-4",
      "gemini",
      "claude",
      "llama",
      "voice assistant",
      "consultation",
      "analysis",
      "treatment",
      "recommendations",
      "24/7",
    ],
    answer:
      "MediCare AI's features significantly enhance healthcare delivery. It includes AI Clinical Decision Support to assist doctors with disease analysis and treatment recommendations, a 24/7 AI Patient Chatbot for history-based patient queries, a Multi-LLM AI Assistant (integrating GPT-4, Gemini, Claude, and Llama) for clinical consultation, and an interactive AI Voice Assistant.",
  },
  {
    keywords: [
      "car",
      "service",
      "management",
      "auto",
      "centers",
      "garage",
      "vehicles",
      "appointments",
      "history",
      "parts",
      "inventory",
      "loyalty",
      "mileage",
      "retention",
    ],
    answer:
      "Our Car Service Management System streamlines all operations for auto service centers and garages. It efficiently manages customers, vehicles, appointments, service history, parts inventory, and client loyalty programs, thereby maximizing operational throughput and boosting customer retention.",
  },
  {
    keywords: [
      "reminders",
      "notifications",
      "alerts",
      "automated",
      "sms",
      "email",
      "mileage requirement",
      "updates",
      "communication",
    ],
    answer:
      "Absolutely! All our systems support automated, real-time notifications and alerts. EduStack facilitates smart parent-school communication; MediCare AI automates appointment reminders and test results; and the Car Service Management System text-alerts customers automatically based on mileage parameters.",
  },
  {
    keywords: [
      "service history",
      "service types",
      "basic",
      "major",
      "brake",
      "tire",
      "ac",
      "general",
      "maintenance",
      "calculate",
      "due date",
      "mileage parameters",
    ],
    answer:
      "Yes! The Car Service Management System tracks complete vehicle lifecycles, maintaining histories for all service types (Basic, Major, Brake, Tire, AC, General). It automatically calculates when the next service is due based on mileage intervals and fires out SMS/email notifications accordingly.",
  },
  {
    keywords: [
      "deployment",
      "cloud",
      "local",
      "server",
      "installation",
      "connected",
      "remote access",
      "scalability",
      "infrastructure",
      "preferences",
      "data control",
    ],
    answer:
      "Yes! All our software solutions offer ultimate deployment flexibility. You can choose cloud-connected systems for seamless remote access and instant scalability, or local server installations for enhanced on-premise data control based on your infrastructure preferences.",
  },
  {
    keywords: [
      "security",
      "secure",
      "code",
      "vulnerability",
      "safety",
      "network",
      "models",
      "non-repudiation",
      "encryption",
      "data",
      "privacy",
      "cyber",
      "protection",
      "safe",
      "assessment",
      "attacks",
      "hipaa",
      "compliant",
      "audit trails",
      "permissions",
      "monitoring",
      "tamper-proof",
      "logging",
    ],
    answer:
      "Security is built into our core DNA across all systems. Our architectural frameworks feature robust end-to-end data encryption, extensive audit trails, role-based access permissions, vulnerability assessments, non-repudiation, and continuous network security monitoring. Notably, MediCare AI is fully HIPAA-compliant with tamper-proof logging to ensure client business and medical data is 100% safe from cyber attacks.",
  },
  {
    keywords: [
      "agile",
      "scrum",
      "methodology",
      "design",
      "patterns",
      "sdlc",
      "process",
      "sprint",
      "project",
      "management",
      "workflow",
      "method",
      "practice",
      "teams",
      "architecture",
    ],
    answer:
      "At Entro Ethiopia, we follow strict modern software engineering theories. We use the Agile and Scrum methodologies, working in 2-week sprints with strict design patterns to guarantee secure, clean, and highly scalable code architecture.",
  },
  {
    keywords: [
      "contact",
      "phone",
      "email",
      "address",
      "location",
      "office",
      "map",
      "info",
      "hours",
      "help",
      "support",
      "call",
      "number",
      "find",
      "reach",
      "addis",
    ],
    answer:
      "You can find or contact us here:\n• Office: Located in Addis Ababa, Ethiopia.\n• Phone: +251 979 113 638\n• Working Hours: Monday to Friday (8:30 AM - 5:30 PM East Africa Time).\n• Email: contact@entroethiopia.com or send a message via our 'Contact Us' page form.",
  },
  {
    keywords: [
      "training",
      "support",
      "installation",
      "configuration",
      "setup",
      "troubleshooting",
      "maintenance",
      "local",
      "ethiopian team",
      "24/7",
      "available",
    ],
    answer:
      "Yes, we provide holistic end-to-end services! This includes complete system installation, tailor-made configuration, extensive user training, and ongoing technical support. Our dedicated local Ethiopian team is available 24/7 to assist with setup, troubleshooting, and maintenance to ensure your team is fully comfortable.",
  },
 
];

export const POPULAR_EMOJIS = [
  "😀",
  "😃",
  "😄",
  "😁",
  "😆",
  "😅",
  "😂",
  "🤣",
  "😊",
  "😇",
  "🙂",
  "🙃",
  "😉",
  "😌",
  "😍",
  "🥰",
  "😘",
  "😗",
  "😙",
  "😚",
  "😋",
  "😛",
  "😝",
  "😜",
  "🤪",
  "🤨",
  "🧐",
  "🤓",
  "😎",
  "🥸",
  "🤩",
  "🥳",
  "😏",
  "😒",
  "😞",
  "😔",
  "😟",
  "😕",
  "🙁",
  "☹️",
  "😣",
  "😖",
  "😫",
  "😩",
  "🥺",
  "😢",
  "😭",
  "😤",
  "😠",
  "😡",
  "👋",
  "👌",
  "👍",
  "👎",
  "👏",
  "🙌",
  "👐",
  "🙏",
  "🤝",
  "❤️",
];
